services:
  db:
    container_name: workflowdb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '3333:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
