import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";


const Home: NextPage = () => {
  const { data: sessionData, status: sessionStatus } = useSession()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {sessionData ?
          <div>
            <p>Hello world!</p>
            <p>{JSON.stringify(sessionData)}</p>
            <button onClick={() => void signOut()}>Sign Out</button>
          </div>
          :
          <button onClick={() => void signIn()}>Sign In</button>

        }

      </main>
    </>
  );
};

export default Home;